const AuthorsListLeft = [
    "Mohamed Abdou",
    "Marina Aksenova",
    "Marie Aronsson",
    "Mohamed Badar",
    "Paul Behrens",
    "Kirsten Bowman",
    "Wenke Brückner",
    "Yassin Brunger",
    "Enrique Carnero-Rojo",
    "Antonio Coco",
    "Gerard Conway",
    "Karel De Meester",
    "Julia Dornbusch",
    "Caroline Ehlert",
    "Ola Engdahl",
    "Viljam Engström",
    "Håkan Friman",
    "Matthew Gillett",
];

const AuthorsListMiddle = [
    "Barbara Goy",
    "Nikola Hajdin",
    "Mikaela Heikkilä",
    "Mayeul Hieramente",
    "Mark Klamberg",
    "Geert-Jan Alexander Knoops",
    "Ruth Kok",
    "Linnea Kortfält",
    "Mateus Kowalski",
    "Camilla Lind",
    "Letizia Lo Giacco",
    "Sally Longworth",
    "Iryna Marchuk",
    "Julie McBride",
    "Yvonne McDermott",
    "Olle Mårsäter",
    "Jonas Nilsson",
    "Anna Öhmichen",
];

const AuthorsListRight = [
    "Joan Pablo Pérez-León- Acevedo",
    "Sara Porro",
    "Noëlle Quénivet",
    "Karin Påle-Bartes",
    "Dejana Radisavljević",
    "Sophie Rigney",
    "Geoff Roberts",
    "Maria Sjöholm",
    "SONG Tianying",
    "Michael Stiel",
    "Ignaz Stegmiller",
    "Carl-Friedrich Stuckenberg",
    "Jenia Iontcheva Turner",
    "Sergey Vasiliev",
    "Aloka Wanigasuriya",
    "ZHANG Binxin",
    "ZHANG Yueyao",
    "Marie Aronsson-Storrier",
];

export const AUTHORS_LIST = [
    ...AuthorsListLeft,
    ...AuthorsListMiddle,
    ...AuthorsListRight,
];

export const DIGEST_EDITORS_LIST = [
    "Fathi Abdel-Raouf",
    "Kai Ambos",
    "Morten Bergsmo",
    "Enrique Carnero-Rojo",
    "Alejandro Chehtman",
    "Julia Grignon",
    "Alexander Heinze",
    "Vickie Iacobellis",
    "Kiki A. Japutra ",
    "Sangkul Kim",
    "Fannie Lafontaine",
    "Justine Levasseur",
    "Maria Luisa Pique",
    "Christian Ranheim",
    "Aleksandra Sidorenko",
    "Alain-Guy Tachou Sipowo",
    "Érick Sullivan ",
    "Ilia Utmelidze",
];

const LecturersFirstColumn = [
    "Hirad Abtahi",
    "Juan Pablo Perez-Leon Acevedo",
    "Xabier Agirre",
    "Marina Aksenova",
    "Pouria Askary",
    "Mohamed S.E.A. Badar",
    "Devasheesh Singh Bais",
    "Horejah Bala-Gaye",
    "Stefan Barriga",
    "Olympia Bekou",
    "Morten Bergsmo",
    "Shikha S. Bhattacharjee",
    "Gilbert Bitti",
    "Enrique Carnero Rojo",
];

const LecturersSecondColumn = [
    "Eleni Chaitidou",
    "Roger Clark",
    "Matthew Cross",
    "Arne Willy Dahl",
    "Mohamed El Zeidy",
    "Donald M. Ferencz",
    "Shannon Fyfe",
    "Matilde Gawronski",
    "Richard J. Goldstone",
    "Gregory S. Gordon",
    "Jens Iverson",
    "Dov Jacobs",
    "Nina Jørgensen",
    "Sangkul KIM",
    "Mark Klamberg",
];

const LecturersThirdColumn = [
    "Linnea Kortfält",
    "Claus Kress",
    "LING Yan",
    "Adel Maged",
    "Christopher Mahony",
    "Yvonne McDermott",
    "Omar A. Mekky",
    "Salim A. Nakhjavani",
    "Jennifer Naouri",
    "Megumi OCHI",
    "Hector Olasolo",
    "Marc Perrin de Brichambaut",
    "Jelena Plamenac",
    "Sara Porro",
    "Klaus Rackwitz",
];

const LecturersFourthColumn = [
    "Dejana Radisavljevic",
    "Rod Rastan",
    "Joseph Rikhof",
    "Geoffrey Roberts",
    "Darryl Robinson",
    "Leila N. Sadat",
    "Beth Van Schaack",
    "William A. Schabas",
    "Jo Stigen",
    "Sepideh Tabatabaei",
    "Melinda Taylor",
    "SONG Tianying",
    "Vladimir Tochilovsky",
    "Mohammad H. Zakerhossein",
    "ZHANG Binxin",
];

export const LECTURERS_LIST = [
    ...LecturersFirstColumn,
    ...LecturersSecondColumn,
    ...LecturersThirdColumn,
    ...LecturersFourthColumn,
];